server:
  port: 8082

spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/activiti?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      db-type: mysql
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      initial-size: 8
      min-idle: 2
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      filters: stat
      use-global-data-source-stat: true
  redis:
    host: localhost
    port: 6379
    password:
  main:
    allow-bean-definition-overriding: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

session:
  timeout: 600000
  algorithmName: MD5
  hashIterations: 2

beetlsql:
  enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #指定服务注册中心的位置
feign:
  httpclient:
    connection-timeout: 10000
